server:
  port: 54264
#  ssl:
#    key-store: classpath:server.pfx # pfk存放路径
#    key-store-type: PKCS12  # tomcat服务器类型默认
#    key-store-password: 542640 # txt密码粘贴即可
  tomcat:
    max-http-form-post-size: 10MB
spring:
  datasource:
    url: jdbc:mysql://localhost:3306/mynas
    password: 1234
    username: root
    driver-class-name: com.mysql.cj.jdbc.Driver
    druid:
      max-active: 100
      max-pool-prepared-statement-per-connection-size: 50
  mvc:
    hiddenmethod:
      filter:
        enabled: true
  servlet:
    multipart:
      max-file-size: 10MB
      max-request-size: 20MB
  profiles:
    active: custom
mybatis-plus:
  configuration:
    map-underscore-to-camel-case: true
